### ISSUE TITLE
Feat: Redesign About Page 

### ISSUE THREAD

**Issue by Aaishpra** [anitab-org/bridge-in-tech-web#127]
## Redesigning of About Page
Propose and develop a new and Better Design for the About Page of Bridge-In-Tech, so that the current one can be replaced.

The Current About page.
![image](https://user-images.githubusercontent.com/66299533/100516881-e5888f00-31ac-11eb-9848-6b56bdec8596.png)

## Describe the solution you'd like

- [ ] Design wireframe using figma/adobe.

- [ ] Get it reviewed/approved

- [ ] Code/Devlop your design

## Describe alternatives you've considered

N/A

## Additional context
Keep Check of the color scheme and navbar

**Comment by prathmeshkhandelwal1** [comment]
@Aaishpra As you opened this issue, are you going to work on this, if not, then @mtreacy002 Can you assign me this?

**Comment by Aaishpra** [comment]
> @Aaishpra As you opened this issue, are you going to work on this, if not, then @mtreacy002 Can you assign me this

Nope, you can take this up, as i am already assigned to other issues at this moment.

**Comment by prathmeshkhandelwal1** [comment]
@mtreacy002 can you assign this to me?

**Comment by mtreacy002** [comment]
sure, @prathmeshkhandelwal1 . It's yours now 😉

**Comment by Palash1999** [comment]
@prathmeshkhandelwal1 are you still working on this?

**Comment by prathmeshkhandelwal1** [comment]
> @prathmeshkhandelwal1 are you still working on this?

yes, I was busy with my exams, So wasn't able to complete it in time, but now i am working on it.

**Comment by prathmeshkhandelwal1** [comment]
@Palash1999 You can take it.

**Comment by sankha555** [comment]
@mtreacy002 @prathmeshkhandelwal1 can I please take this up if no one else is working on it? Thanks!

**Comment by mtreacy002** [comment]
Hi @prathmeshkhandelwal1 , @Palash1999 , and @sankha555 , since we're in the process of redesigning the pages throughout BIT to match the AnitaB guidelines, we need to put this PR on hold for now till we've come up with a clearer design matrix for BIT. Sorry for the inconvenience. But you can still involve in the design process by joining the Design Open Session. At the moment we're taking a step back and focusing on [redesigning the Navbar](https://anitab-org.zulipchat.com/#narrow/stream/237630-bridge-in-tech/topic/Design.20of.20BIT/near/222895673) first before moving to the pages. Also, please join the #bridge-in-tech channel on Zulip. There is a` Design of BIT` topic under that channel that discussing this matter. Thank you so much for your understanding.

**Comment by mtreacy002** [comment]
Closing this issue now as we've selected the design for the Homepage and the `About` section is no longer needed.
