### ISSUE TITLE
Feat: Redesign Benefit Page

### ISSUE THREAD

**Issue by Aaishpra** [anitab-org/bridge-in-tech-web#128]
## Redesign Benefit Page
Propose and develop a new and Better Design for the Benefit Page of Bridge-In-Tech, so that the current one can be replaced.

The current Benefit Page.
![image](https://user-images.githubusercontent.com/66299533/100517066-27660500-31ae-11eb-9532-f7e319ec67bb.png)

## Describe the solution you'd like

- [ ] Design the wireframe for the page using figma/adobe.

- [ ] Get it reviewed/approved

- [ ] Code/Devlop your design

## Describe alternatives you've considered
N/A

## Additional context
Please take care of the colour scheme of the project and navbar while designing.

**Comment by marthaerm** [comment]
Hey! I would like to work on this issue with @marianayap help, @mtreacy002 may you assign it to us?

**Comment by marianayap** [comment]
Hello! I will love to work on the issue with Martha as well! @mtreacy002

**Comment by mtreacy002** [comment]
@marthaerm and @marianayap , both of you can work on it 😉. Thanks for picking it up.

**Comment by marianayap** [comment]
@mtreacy002 Thank you:)

**Comment by marianayap** [comment]
Hello! @mtreacy002  @marthaerm  and I have been working on this approach for the benefit page. Also, we have a question about the bottom page image, where did you get it? we would like to keep the same chef concept but a different illustration. We'll wait for the confirmation to start coding it. Thank you!
![WhatsApp Image 2020-12-15 at 2 24 51 PM](https://user-images.githubusercontent.com/19355313/102288173-2c8aba00-3ef9-11eb-80a0-9ff704c683dd.jpeg)

**Comment by mtreacy002** [comment]
@marianayap, the proposed design looks good. As for thee esource of bottom image, here's the [link](https://images.app.goo.gl/JutinVTdeKvv4oFR9) where I got it from.

**Comment by mtreacy002** [comment]
Hi @marianayap and @marthaerm, since we're in the process of redesigning the pages throughout BIT to match the AnitaB guidelines, we need to put this PR on hold for now till we've come up with a clearer design matrix for BIT. Sorry for the inconvenience. But you can still involve in the design process by joining the Design Open Session. At the moment we're taking a step back and focusing on [redesigning the Navbar](https://anitab-org.zulipchat.com/#narrow/stream/237630-bridge-in-tech/topic/Design.20of.20BIT/near/222895673) first before moving to the pages. Also, please join the #bridge-in-tech channel on Zulip. There is a` Design of BIT` topic under that channel that discussing this matter. Thank you so much for your understanding.

**Comment by mtreacy002** [comment]
Closing this issue now as we've selected the design for the Benefit section (issue #211).
