### ISSUE TITLE
Refactor Register Component Code

### ISSUE THREAD

**Issue by harsha-sam** [anitab-org/bridge-in-tech-web#139]
## Description
As a member,
I need to understand how the state of a component works and changes,
so that I can further contribute to the project.

### Update [Required]
- [ ] Replacing multiple useState hooks in Register component with a useReducer hook for better state management, code readability, and optimization.
- [ ] Only Register Component should be changed.
## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
1 Day

**Comment by jalajcodes** [comment]
Can I work on it?

**Comment by harsha-sam** [comment]
I already worked on it @jalajcodes 😄. I made a PR without opening the issue earlier. So, I opened the issue according to the guidelines and waiting for approval from @mtreacy002.

**Comment by mtreacy002** [comment]
@Rage-ops , can you please help further explain why we need to refactor the useState to useReducer (like the extra benefit it will have over useState and perhaps the pros and cons of what both useState/useReducer might cause to the application). Just bcoz I'm interested to learn more about this. Thanks beforehand.

**Comment by harsha-sam** [comment]
Sure @mtreacy002. Firstly, instead of handling validity individually for every field, we can handle all field validity just by dispatching the same action type, so multiple handle callbacks aren't needed. useReducer gives us more predictable state transitions than useState. For example, if we are using setState() calls in succession, we can't assure that all those updates gonna take place at the same time. But with useReducer, we can encapsulate those changes in a reducer function that dispatches all of them as a single action. And even if the logic grows in the future, useReducer is always preferable for complex state logic and it optimizes overall performance.

**Comment by mtreacy002** [comment]
> Sure @mtreacy002. Firstly, instead of handling validity individually for every field, we can handle all field validity just by dispatching the same action type, so multiple handle callbacks aren't needed. useReducer gives us more predictable state transitions than useState. For example, if we are using setState() calls in succession, we can't assure that all those updates gonna take place at the same time. But with useReducer, we can encapsulate those changes in a reducer function that dispatches all of them as a single action. And even if the logic grows in the future, useReducer is always preferable for complex state logic and it optimizes overall performance.

It makes sense to me, although, since I’m still a newbie in React, I’d like to get a second opinion from others with more React knowledge. @annabauza or @meenakshi-dhanani , can you please help us with your thoughts on this useState to useReducer refactoring? Thanks beforehand.

**Comment by mtreacy002** [comment]
@harsha-sam , can you please check the Zulip post feedback [here](https://anitab-org.zulipchat.com/#narrow/stream/223071-newcomers/topic/Advice.20Needed/near/223199738) from Rahul Mohata. 
Considering that we're still in a very early stage of the development, I think we should wait the refactoring to useReducer until we've got more features to tackle. At this stage, my focus is on completing the MVP with the next feature on the frontend we need to tackle is around creating mentorship relation ( such as giving user the ability to apply to a mentoring program). Nevertheless, you've raised a vary valid point that wee need to tackle in the near future. 
For now I will label this issue as `Status: On Hold` so that when we're ready, we can go back to this.

**Comment by mtreacy002** [comment]
@harsha-sam , the discussion on the useReducer() is now moved to the Outreach/Research issue #217 . So, I'm closing this issue here. Feel free to join the discussion there, or **if you want, you can claim the issue as well** since **Outreach/Research type of issues can be assigned to more than one contributor**. We will go through contributors suggestions and select the best approach. cc @anitab-org/osh .
