### ISSUE TITLE
Bug: Login and signup button overlaps 

### ISSUE THREAD

**Issue by nlok5923** [anitab-org/bridge-in-tech-web#142]
**Describe the bug**
Login and signup button overlaps in login page.

**To Reproduce**
1. Go to Home
2. Click on Login
3. See error

**Expected behavior**
Button should be inline with space between

**Screenshots**
![image](https://user-images.githubusercontent.com/56120084/104541258-47ab2f80-5647-11eb-86f5-0d6ff85e7b59.png)

**Desktop (please complete the following information):**
 - OS: All
 - Browser All
 - Version All

**Smartphone (please complete the following information):**
 - Device: none
 - OS: none
 - Browser none
 - Version none

**Comment by nlok5923** [comment]
i would like to resolve it.

**Comment by Aaishpra** [comment]
@mtreacy002 I think this issue is the same as #131 and was already solved by #132 but how come this bug still exists.
I checked and found the same.
![image](https://user-images.githubusercontent.com/66299533/104552879-9f559500-565f-11eb-9250-8ac54ebd31a8.png)

**Comment by mtreacy002** [comment]
You’re right, @Aaishpra. This issue has been resolved. @nlok5923 , you’re 2 commits behind the develop branch (so the issue #132 that you’ve fixed didn’t get applied on your fork repo). Please pull from upstream and check again. If the issue no longer there, please close this issue. Thanks 😉

**Comment by nlok5923** [comment]
@mtreacy002 i checked my fork is updated with develop branch. It is solved in #132 but still it is there .

**Comment by mtreacy002** [comment]
That's strange. Ok, I'll check it locally then when I get back home (don't have my laptop with me atm) 😆. Will get back to you on this 😉

**Comment by Aaishpra** [comment]
> That's strange. Ok, I'll check it locally then when I get back home (don't have my laptop with me atm) laughing. Will get back to you on this wink

@nlok5923 is right, I checked it on my browser and found the same.

**Comment by Ayush23Dash** [comment]
@nlok5923 @mtreacy002 @Aaishpra this is a media query error. I removed it and now it is working fine.


https://user-images.githubusercontent.com/40827680/104580622-8068fa00-5683-11eb-9563-f77c45329086.mp4

**Comment by Ayush23Dash** [comment]
Hey @nlok5923 ,can you please inform about why did you close it?

**Comment by nlok5923** [comment]
Sorry @Ayush23Dash my bad.

**Comment by mtreacy002** [comment]
@nlok5923, @Ayush23Dash and @Aaishpra. I've run it locally and you're right, the Login page `Login and Signup` button are showing a different behaviour to the fix in #132 (you can see the gif I posted there when I did the test).

From my test just now, only the Register page showing the expected behaviour (although wheen the screen is < 322, the buttons start stacking up).
![ezgif com-gif-maker (21)](https://user-images.githubusercontent.com/29667122/104661745-4ea47180-571d-11eb-8e57-a41349acfaba.gif)

However, the Login page shows the buttons are stacking up when the screen goes beyond 600, and only shows the expected behaviour when it is < 600.
![ezgif com-gif-maker (22)](https://user-images.githubusercontent.com/29667122/104661887-a642dd00-571d-11eb-970e-acdde693ce8f.gif)

What strange though, these two behaviours (on Register and Login pages) were not the same as when I tested #132. I wonder how this happen 🤔 ?? 
Anyway, I consider this issue as legit, so, @nlok5923, I'll assign you to this. But if you could also investigate how the behaviours of these 2 pages change as well, that would be helpful. This way we could prevent similar thing happens in the future.

Thanks beforehand.

**Comment by nlok5923** [comment]
Sure @mtreacy002 i will investigate the reason behind the same. 😊

**Comment by Ayush23Dash** [comment]
Hi @nlok5923 ,can you please tell if this is resolved with the PR you linked?

**Comment by nlok5923** [comment]
@Ayush23Dash yes the linked pr resolves this issue.

**Comment by Aaishpra** [comment]
> Hi @nlok5923 ,can you please tell if this is resolved with the PR you linked?

You can test and review that by yourself too @Ayush23Dash and give your feedback in the linked PR.

**Comment by shades-7** [comment]
@nlok5923 hey, is this still open, can I work on it?

**Comment by nlok5923** [comment]
@shades-7 there's already a pr addressing this issue.

Thanks
