### ISSUE TITLE
Bug : Personal Details

### ISSUE THREAD

**Issue by Rahulm2310** [anitab-org/bridge-in-tech-web#154]
**Describe the bug**
When I try to edit and save my personal details, it says a user with username already exists although I am not changing my username or email.

**To Reproduce**
1. Go to My Space/Profile/Personal Details
2. Scroll Down
3. Click on Save Button

**Expected behavior**
It should update the user's personal details correctly.

**Screenshots**
Here's a gif describing the issue :
![personal-details](https://user-images.githubusercontent.com/54268438/105497474-e63d2d80-5ce4-11eb-8ac3-17800ef9940c.gif)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser : Chrome
 - Version: 87.0.4280.141

If this is not the intended behavior, I would like to work on this issue.

**Comment by mtreacy002** [comment]
@Rahulm2310 , this issue is a backend issue and a cross project issue with Mentorship System. This issue has been raised on the [BIT backend repo](https://github.com/anitab-org/bridge-in-tech-backend/issues/141https://github.com/anitab-org/bridge-in-tech-backend/issues/141) and is put on hold since we can only move ahead with it once the Mentorship System issue referred in it has done the fix. So, you can close this issue now.

**Comment by Rahulm2310** [comment]
Alright @mtreacy002 ! Thanks for looking into it.
