### ISSUE TITLE
Doc: Fix Typos in Readme

### ISSUE THREAD

**Issue by 0xNilesh** [anitab-org/bridge-in-tech-web#156]
**Describe the bug**
1. Some spelling mistakes are there.
2. Some commas and verbs are missing in the readme file.

**Screenshots**
![1issue](https://user-images.githubusercontent.com/54444545/105613443-9051ae00-5de8-11eb-9b90-d1e31b763142.JPG)

![2issue](https://user-images.githubusercontent.com/54444545/105613452-98115280-5de8-11eb-944d-e4b7dbf90511.JPG)

![3issue](https://user-images.githubusercontent.com/54444545/105613458-9d6e9d00-5de8-11eb-898b-b4b0cc76eae6.JPG)

Some are shown in the screenshots and some others are also there.

**Comment by 0xNilesh** [comment]
Please assign me for this issue.

**Comment by mtreacy002** [comment]
@VectoTec , thank you for raising this. For issue related to grammatical error/typo, we consider it as a minor issue that is best to be left for a first timer contributor (which you are no longer considered as since you've done your first time contribution through issue #151). Also, I prefer if we can take notes on any grammatical/typo errors first and do the fix in one go when we have enough errors to be fixed, unless it is a typo/error that could lead to a misinformation (such as issue [179 backend](https://github.com/anitab-org/bridge-in-tech-backend/issues/179)). 
I've just opened a [google doc](https://docs.google.com/document/d/12wqYtC8JvhFPqk8-k6T72c9PNZzzch3HW6Zo38jUjw0/edit), added your findings and placed it on the wiki page side bar (under `Minor issues`) for this type of issue. So, you can close this issue now.

**Comment by 0xNilesh** [comment]
Okay fine, I'll put other errors in the google doc for first timers. For now, I'm closing this issue.☺️
