### ISSUE TITLE
Bug: Spelling and Grammatical errors in some doc files

### ISSUE THREAD

**Issue by shruti1421** [anitab-org/bridge-in-tech-web#161]
**Describe the bug**
There are some spelling and grammatical in the readme file

**To Reproduce**
1. Go to '...Readme.md'

**Expected behavior**

**Screenshots**
In Readme.md
![image](https://user-images.githubusercontent.com/64346825/105742222-3aecdc80-5f61-11eb-9f2d-9a09687d840d.png)

In Reporting Guidelines.md
![image](https://user-images.githubusercontent.com/64346825/105743137-5b696680-5f62-11eb-8c32-1268878489b9.png)
there should be comma after cases.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Rahulm2310** [comment]
@shruti1421 Thanks for showing interest in fixing bugs. A suggestion I would like to give you is when contributing to an open source project, try to be patient and let the maintainers approve /confirm the bugs even if they are crystal clear or very small.  This way both maintainers & contributors will be at ease.

**Comment by mtreacy002** [comment]
@shruti1421 , in an open source, It is important to follow the workflow of the open source organization you're contributing to. The workflow of BIT can be seen on the [Getting Started > Choosing a working item](https://github.com/anitab-org/bridge-in-tech-web/wiki/Getting-Started#choose-a-working-item) guideline. As stated in the guideline (and mentioned by @Rahulm2310 above), once you raised an issue, you need to wait for a maintainer to approve the issue and assign you to it before you can start working. 

Similar issue had been raised by @VectoTec on issue #156 and [here's](https://github.com/anitab-org/bridge-in-tech-web/issues/156#issuecomment-766190021) my suggestion to the issue. Hence, you could add your findings to the doc mentioned in my post and close this issue for now 😉.

PS: It is understandable that you might have overlooked the guideline provided to new contributors since you are only just started contributing to the project, so don't stress about this mistake 😉.

**Comment by shruti1421** [comment]
I'm very sorry for this mistake. 
I've just started contributing to open source projects that's why I didn't knew I've to follow contributing guidelines.I'm closing this issue now.

**Comment by mtreacy002** [comment]
No worries, @shruti1421 . Don't forget to add your findings on the [doc](https://docs.google.com/document/d/12wqYtC8JvhFPqk8-k6T72c9PNZzzch3HW6Zo38jUjw0/edit) referred above 😉
