### ISSUE TITLE
clean: Remove redundant GETTING_STARTED.md file under the .github folder

### ISSUE THREAD

**Issue by Rahulm2310** [anitab-org/bridge-in-tech-web#200]
### Describe the bug
We havea [Getting_Started.md](https://github.com/anitab-org/bridge-in-tech-web/wiki/Getting-Started) file under the project's GitHub wiki. But there is another Getting_Started.md file under the .github folder which is redundancy.

### To Reproduce
1. Go [here](https://github.com/anitab-org/bridge-in-tech-web/blob/develop/.github/GETTING_STARTED.md).
2. See error

### Expected behavior
This file is redundant and thus should be removed.

### Desktop (please complete the following information):
 - OS: Any
 - Browser: Any
 - Version: Any

**Comment by mtreacy002** [comment]
@Rahulm2310 , this is not a redundant file. The .md files under .github folder are meant to give access to contributors to the content of wiki pages so they can contribute to them (modifying/adding new one) from there (since only maintainers have write access to wiki pages. Our aim is to remove all the static pages under wiki and get the content for that page by referring to the .md files. What we can do for OSH is to open documentation issues to create .md relevant to wiki pages. So when the PRs get approved, I can link them to the wiki (instead of using wiki pages). This is also will be the case for BIT backend wiki. So, you can close the issue now 😉.

**Comment by Rahulm2310** [comment]
@mtreacy002  Sure 😊. Will help in opening the documentation issues. Closing this.
