### ISSUE TITLE
Test: Write tests for input validations on the Register form

### ISSUE THREAD

**Issue by meenakshi-dhanani** [anitab-org/bridge-in-tech-web#28]
## Description
The Register component has many input fields. And it raises or displays a validation message if any of the inputs are not according to the format expected. 

## Acceptance Criteria
- [ ] Write tests using React Testing Library in the Register.test.js file 
- [ ] Test if validation message shows up for name 
- [ ] Test if validation message shows up for username
- [ ] Test if validation message shows up for email
- [ ] Test if validation message shows up for password

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 2 mentor.

## Estimation
3 hours

**Comment by Aaishpra** [comment]
hey can u assign this to me @meenakshi-dhanani

**Comment by mtreacy002** [comment]
@Aaishpra . You've already been assigned to issue #66 . So, we'll keep this one open for others to pickup. 😁

**Comment by Aaishpra** [comment]
sorry, @mtreacy002 I guess I wouldn't be able to work on that but this issue belongs to my field of knowledge and I will be able to work on this so please assign this to me and I have already unassigned from #66 .
Sorry for inconvenience

**Comment by mtreacy002** [comment]
That's OK, @Aaishpra . I'll assign you to this one then. Thanks for letting me know. 👍

**Comment by mtreacy002** [comment]
@Aaishpra. Can you please give an update on your progress on this issue? Just in case you need help with anything. 😉

**Comment by Aaishpra** [comment]
Hey @mtreacy002 sorry for no updates still working on that i think it will be completed in 2 days and i will make a pr then .

**Comment by mtreacy002** [comment]
No worries, @Aaishpra . Just checking because I'm tidying up the repository atm. Take your time 😉

**Comment by Aaishpra** [comment]
@mtreacy002 do i need to make seprate tests for testing seprate fields

**Comment by mtreacy002** [comment]
@Aaishpra, I think it's best to have them separate, since on the UI, the warning will be given on the first incorrect field found. For example, if the name and the username are wrong, the warning only will show that the name is wrong, the username is not checked. If the name is then corrected, then it'll check for the next field which is username. Does this make sense?

cc @meenakshi-dhanani , do we want to check this on all the required fields that have validation in place or two or three tests will suffice? Imo few tests should do at this stage. Let me know what you think.

**Comment by Aaishpra** [comment]
Yes sure will make seprate tests for each field

**Comment by mtreacy002** [comment]
Although, @Aaishpra . You could also do one for all fields in one test where the error message  are shown in red text per each field (see screenshot below)
<img width="1151" alt="Screen Shot 2020-09-01 at 2 27 37 pm" src="https://user-images.githubusercontent.com/29667122/91794829-604e1680-ec5f-11ea-9afc-4b82b56a4d1b.png">


Notice that a warning that check for blank fields comes one field at a time from the first error field found.

So, perhaps do one for the input validation for all fields (with red error texts) and one for an empty field warning. What do you think?

**Comment by Aaishpra** [comment]
@mtreacy002 I couldn't find where this warning for the empty field " Please fill in this field " is written. Can u help me with this?

**Comment by mtreacy002** [comment]
@Aaishpra . That comes from the use of html `required` attribute as shown in the code below

<img width="821" alt="Screen Shot 2020-09-01 at 3 29 15 pm" src="https://user-images.githubusercontent.com/29667122/91798502-5ed51c00-ec68-11ea-8dac-d016959ed458.png">

@testing-library/jest-dom has [.toBeRequired()](https://github.com/testing-library/jest-dom#toberequired) to check this attribute. Hope this helps 😉

**Comment by Aaishpra** [comment]
![image](https://user-images.githubusercontent.com/66299533/91873182-5bf12000-ec96-11ea-96a6-3f32a3484d20.png)
Don't know why I am getting this, In my view there is only one element that contains placeholder "Username"

**Comment by mtreacy002** [comment]
@Aaishpra , there's an example on PersonalDetails.test.js line 51 on how to use getByLabelText narrowing down using the `selector`
<img width="866" alt="Screen Shot 2020-09-02 at 4 02 43 pm" src="https://user-images.githubusercontent.com/29667122/91937800-15530280-ed36-11ea-950b-1cd5c4dfb96c.png">

Noticed that in PersonalDetails.jsx, the `label` is used with `id` instead of `htmlFor` and `input` has an `aria-labelledBy` attribute to make the referencing works. Can you give this a try and see of it works.

**Comment by mtreacy002** [comment]
@Aaishpra, if you could send a PR with the current code you have (it doesn't matter if it's not quite right yet, you could add label `WIP | ...<PR title>` at the beginning of your PR, to help give me a clearer picture on where your code might have gone wrong. Can you do that?

**Comment by Aaishpra** [comment]
Done @mtreacy002
