### ISSUE TITLE
View User Profile - Additional Information

### ISSUE THREAD

**Issue by meenakshi-dhanani** [anitab-org/bridge-in-tech-web#35]
## Description
As a registered user,
I want to see my profile - additional information,
so that I can update it in the future when necessary.

## Mocks
#5 

## Acceptance Criteria
- [ ] Additional profile information details - phone, mobile, number, personal website, etc. should be displayed
- [ ] Tests for display of each of these fields must be present

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 2 mentor.

**Comment by meenakshi-dhanani** [comment]
Are you sure @mtreacy002 you want to do the upload resume in the mockup as part of the MVP or part of this story?

**Comment by mtreacy002** [comment]
@meenakshi-dhanani , the fields on BIT only resemble what MS has as fields on their form. BIT is tightly coupled with MS in that sense in that all fields in MS need to be in BIT otherwise partial data that BIT sending will be considered invalid data. 
But BIT can take few things out of the responses from MS (like I did with the refresh-token and refresh-expiry).
 @isabelcosta probably can answer why the fields are needed in this case. if we want to exclude any fields, the change must be done from MS side first before we can apply it to BIT side. cc @anitab-org/bridgeintech-maintainers what're you're opinion on this?

**Comment by mtreacy002** [comment]
I can take out any fields that are not currently on MS such as phone, mobile number and personal website from additional information. That Additional information can just be for the important 2 information BIT must have: timezone and if user is_organization_rep.
I put the phone, mobile number and personal website as `not required` anyway on the form.

<img width="930" alt="Screen Shot 2020-07-11 at 10 35 21 am" src="https://user-images.githubusercontent.com/29667122/87212528-58aa7980-c362-11ea-8457-328e84b3a238.png">

I add them there since I'm thinking if a company want to `hire` someone to be a mentor/mentee of the program they offer, they would like to establish a form of contact with that person that is not just email. Just like in our resume, we'll give our phone number and personal website url as well as email just so the organization we're applying to can choose whichever method to contact us. This is just my opinion.

**Comment by mtreacy002** [comment]
We can also hide some user's personal details like phone, mobile phone, resume and photo urls on the Member Portfolio page if user viewing the profile page is not the owner of the profile. But we can include those details on the Program application form when the user is applying to a Mentoring program. What do you all  think?

**Comment by meenakshi-dhanani** [comment]
Whatever works for you, without having to make a change in MS for now. If MS returns some fields we can show whatever MS get call returns. For the future however, for MS it would make sense to have the same details in get and post calls.
