### ISSUE TITLE
Bug: add missing payload to pass expected fields validation check backend

### ISSUE THREAD

**Issue by mtreacy002** [anitab-org/bridge-in-tech-web#55]
**Describe the bug**
Backend code has been modified by adding the expected fields validation check which means if frontend payload does not match request body, it will response with error code Bad reequest (400)

**To Reproduce**
1. Go to Register and register as a new user with only one availability checked ("available as mentor" or "need mentoring", but not both)
2. Submit the form and see the error response below:
"Unexpected input is detected. Please check your input to make sure only approved fields are to be submitted."

**Expected behavior**
No error message should be returned since availability options are optional.

**Screenshots**
<img width="1047" alt="Screen Shot 2020-07-27 at 1 52 31 pm" src="https://user-images.githubusercontent.com/29667122/88504164-30d03c80-d017-11ea-9c3d-a0e8bd8618d0.png">

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Chrome
 - Version ?

**Additional context**
NA

**Comment by meenakshi-dhanani** [comment]
Hey @mtreacy002 , when you describe the bug instead of making the description very technical you can focus on what exactly is the problem from a business perspective. 
eg. If we select either of the two options, the input is still invalid. 

And in notes or something, you can mention technical details. 
Diving right into the implementation, makes it difficult to read through the issue
